apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: web
  template:
    metadata:
      labels:
        app: todoapp
        name: web
    spec:
      containers:
      - name: myweb
        image: techproawsdevopsteam/todoapp:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: todo